- name: 클라우드타입 자동 재배포
  uses: cloudtype-github-actions/deploy@v1
  with:
    token: ${{ secrets.CLOUDTYPE_TOKEN }}
    project: rator9521/mytech
    stage: main
    yaml: |
      name: mytech
      app: python@3.10
      build:
        commands:
          - pip install -r requirements.txt
      run:
        - gunicorn --bind 0.0.0.0:8000 --workers 1 --timeout 120 main:app
      context:
        git:
          url: git@github.com:Masonleent/Mytech.git
          ref: main